---
- name: setting up mediawiki-docker compose
  hosts: localhost
  vars: 
     ip: "{{ ansible_default_ipv4.address }}"
  connection: local
  become: true
  tasks:
  - name: Creating a new swarm cluster
    command: docker swarm init
  - name: Fetching swarm cluster manager token
    command: docker swarm join-token worker -q
    register: info
  - name: Creating Swarm overlay network - proxy
    command: docker network create -d overlay proxy
  - name: Print details
    debug:
        msg: " {{ info.stdout }}"
  - name: write a token to a file to be used to join worker nodes
    local_action: shell echo -n "{{ info.stdout }} {{ ip }}:2377" > "/tmp/token"
    become: false
  
  - name: Giving permission
    local_action: shell chmod 777 token
    sudo: False